[2023-10-11 15:50:12,307] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: tf_pipeline.data_validation 2023-10-11T15:48:49.722957+00:00 [queued]>
[2023-10-11 15:50:12,339] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: tf_pipeline.data_validation 2023-10-11T15:48:49.722957+00:00 [queued]>
[2023-10-11 15:50:12,339] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-10-11 15:50:12,340] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2023-10-11 15:50:12,340] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-10-11 15:50:12,356] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): data_validation> on 2023-10-11T15:48:49.722957+00:00
[2023-10-11 15:50:12,388] {standard_task_runner.py:52} INFO - Started process 9337 to run task
[2023-10-11 15:50:12,399] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'tf_pipeline', 'data_validation', '2023-10-11T15:48:49.722957+00:00', '--job-id', '13', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmp5g872hci', '--error-file', '/tmp/tmpxeux2cl1']
[2023-10-11 15:50:12,410] {standard_task_runner.py:77} INFO - Job 13: Subtask data_validation
[2023-10-11 15:50:12,497] {logging_mixin.py:104} INFO - Running <TaskInstance: tf_pipeline.data_validation 2023-10-11T15:48:49.722957+00:00 [running]> on host 0e092fd43c1f
[2023-10-11 15:50:12,609] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tf_pipeline
AIRFLOW_CTX_TASK_ID=data_validation
AIRFLOW_CTX_EXECUTION_DATE=2023-10-11T15:48:49.722957+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-11T15:48:49.722957+00:00
[2023-10-11 15:50:12,612] {python.py:151} INFO - Done. Returned value was: None
[2023-10-11 15:50:12,632] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=tf_pipeline, task_id=data_validation, execution_date=20231011T154849, start_date=20231011T155012, end_date=20231011T155012
[2023-10-11 15:50:12,692] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-10-11 15:50:12,725] {local_task_job.py:151} INFO - Task exited with return code 0
