[2023-10-11 16:14:13,949] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: tf_pipeline.data_validation 2023-10-11T16:13:20.567811+00:00 [queued]>
[2023-10-11 16:14:13,977] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: tf_pipeline.data_validation 2023-10-11T16:13:20.567811+00:00 [queued]>
[2023-10-11 16:14:13,977] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-10-11 16:14:13,977] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2023-10-11 16:14:13,978] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-10-11 16:14:13,993] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): data_validation> on 2023-10-11T16:13:20.567811+00:00
[2023-10-11 16:14:14,007] {standard_task_runner.py:52} INFO - Started process 638 to run task
[2023-10-11 16:14:14,014] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'tf_pipeline', 'data_validation', '2023-10-11T16:13:20.567811+00:00', '--job-id', '20', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpydvgumzm', '--error-file', '/tmp/tmpiab8sthn']
[2023-10-11 16:14:14,019] {standard_task_runner.py:77} INFO - Job 20: Subtask data_validation
[2023-10-11 16:14:14,086] {logging_mixin.py:104} INFO - Running <TaskInstance: tf_pipeline.data_validation 2023-10-11T16:13:20.567811+00:00 [running]> on host 8ca10712e9bf
[2023-10-11 16:14:14,169] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tf_pipeline
AIRFLOW_CTX_TASK_ID=data_validation
AIRFLOW_CTX_EXECUTION_DATE=2023-10-11T16:13:20.567811+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-11T16:13:20.567811+00:00
[2023-10-11 16:14:14,172] {python.py:151} INFO - Done. Returned value was: None
[2023-10-11 16:14:14,189] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=tf_pipeline, task_id=data_validation, execution_date=20231011T161320, start_date=20231011T161413, end_date=20231011T161414
[2023-10-11 16:14:14,239] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-10-11 16:14:14,264] {local_task_job.py:151} INFO - Task exited with return code 0
