[2023-10-11 15:04:44,810] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: tf_pipeline.data_validation 2023-10-11T15:04:08.993879+00:00 [queued]>
[2023-10-11 15:04:44,845] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: tf_pipeline.data_validation 2023-10-11T15:04:08.993879+00:00 [queued]>
[2023-10-11 15:04:44,845] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-10-11 15:04:44,845] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2023-10-11 15:04:44,845] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-10-11 15:04:44,867] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): data_validation> on 2023-10-11T15:04:08.993879+00:00
[2023-10-11 15:04:44,881] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'tf_pipeline', 'data_validation', '2023-10-11T15:04:08.993879+00:00', '--job-id', '5', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmp9bwek7dv', '--error-file', '/tmp/tmpbydfa88r']
[2023-10-11 15:04:44,875] {standard_task_runner.py:52} INFO - Started process 5297 to run task
[2023-10-11 15:04:44,882] {standard_task_runner.py:77} INFO - Job 5: Subtask data_validation
[2023-10-11 15:04:44,957] {logging_mixin.py:104} INFO - Running <TaskInstance: tf_pipeline.data_validation 2023-10-11T15:04:08.993879+00:00 [running]> on host 0e092fd43c1f
[2023-10-11 15:04:45,126] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tf_pipeline
AIRFLOW_CTX_TASK_ID=data_validation
AIRFLOW_CTX_EXECUTION_DATE=2023-10-11T15:04:08.993879+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-11T15:04:08.993879+00:00
[2023-10-11 15:04:45,129] {python.py:151} INFO - Done. Returned value was: None
[2023-10-11 15:04:45,154] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=tf_pipeline, task_id=data_validation, execution_date=20231011T150408, start_date=20231011T150444, end_date=20231011T150445
[2023-10-11 15:04:45,211] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-11 15:04:45,258] {local_task_job.py:151} INFO - Task exited with return code 0
