[2023-10-11 16:51:14,939] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: tf_pipeline.data_validation 2023-10-11T16:50:22.286375+00:00 [queued]>
[2023-10-11 16:51:14,968] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: tf_pipeline.data_validation 2023-10-11T16:50:22.286375+00:00 [queued]>
[2023-10-11 16:51:14,968] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-10-11 16:51:14,969] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2023-10-11 16:51:14,969] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-10-11 16:51:14,983] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): data_validation> on 2023-10-11T16:50:22.286375+00:00
[2023-10-11 16:51:14,999] {standard_task_runner.py:52} INFO - Started process 876 to run task
[2023-10-11 16:51:15,011] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'tf_pipeline', 'data_validation', '2023-10-11T16:50:22.286375+00:00', '--job-id', '24', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpqnp3dxa5', '--error-file', '/tmp/tmpk80_h1a3']
[2023-10-11 16:51:15,018] {standard_task_runner.py:77} INFO - Job 24: Subtask data_validation
[2023-10-11 16:51:15,093] {logging_mixin.py:104} INFO - Running <TaskInstance: tf_pipeline.data_validation 2023-10-11T16:50:22.286375+00:00 [running]> on host 75f5fce176ac
[2023-10-11 16:51:15,193] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tf_pipeline
AIRFLOW_CTX_TASK_ID=data_validation
AIRFLOW_CTX_EXECUTION_DATE=2023-10-11T16:50:22.286375+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-11T16:50:22.286375+00:00
[2023-10-11 16:51:15,197] {python.py:151} INFO - Done. Returned value was: None
[2023-10-11 16:51:15,217] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=tf_pipeline, task_id=data_validation, execution_date=20231011T165022, start_date=20231011T165114, end_date=20231011T165115
[2023-10-11 16:51:15,312] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-11 16:51:15,377] {local_task_job.py:151} INFO - Task exited with return code 0
